version: "3.7"
services:
  nginx:
    build: ./api
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/laravel
    depends_on:
      - db

  db:
    image: mysql:5.6
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: laravel
      MYSQL_USER: rqw
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql